// Standalone commercial-intent landing pages (as opposed to the informational
// articles in blogPosts.js). Each entry becomes a real top-level route
// (e.g. /tractor-booking) wired through SeoCanonical.jsx for meta tags plus
// Service + FAQPage schema. Add new routes here AND in App.jsx AND
// public/sitemap.xml.
const servicePages = [
  {
    slug: 'tractor-booking',
    emoji: '🚜',
    title: 'Tractor Booking Service in India | GaonConnect',
    metaDescription: 'Tractor booking service — apne gaon ke paas tractor near me book karein. Jutai, boni aur khet ke har kaam ke liye verified tractor owners, ek hi app mein.',
    keywords: 'tractor booking, tractor booking service, tractor near me, tractor booking online, book a tractor, kisan gadi booking',
    heroTitle: 'Tractor Booking Service',
    heroSubtitle: 'Jutai, boni ya khet ke kisi bhi kaam ke liye — apne gaon ke paas tractor turant book karein.',
    intro: [
      'GaonConnect par tractor booking service Madhya Pradesh ke gaon aur dehat ke kisano ke liye banayi gayi hai. Ek hi app se, apne aas-paas ke verified tractor owners ki list dekhkar, chand minute mein booking confirm kar sakte hain.',
      'Chahe rotavator se jutai karwani ho, cultivator se khet taiyar karna ho, ya thresher attachment ke saath fasal ka kaam — sab GaonConnect par available hai.',
    ],
    benefits: [
      { title: 'Turant Availability', description: 'Apne gaon ke aas-paas jitne bhi tractor registered hain, unki live availability turant dikhti hai.' },
      { title: 'Fair, Transparent Rate', description: 'Booking se pehle hi estimated fare pata chal jaata hai — koi hidden charge nahi.' },
      { title: 'Verified Owners', description: 'Sabhi tractor owners ki details GaonConnect par verify ki jaati hain.' },
      { title: 'Sabhi Implements', description: 'Rotavator, cultivator, thresher attachment — jo bhi implement chahiye, wahi tractor book karein.' },
    ],
    faqs: [
      { question: 'Tractor booking ka rate kaise tay hota hai?', answer: 'Rate ghante ya bigha/acre ke hisaab se, kaam ke type aur implement ke aadhar par tay hota hai. Booking se pehle hi estimated fare app mein dikh jaata hai.' },
      { question: 'Kya main apne gaon ke aas-paas ka tractor near me dhoondh sakta hoon?', answer: 'Haan, app apki location ke aas-paas available tractors ki list turant dikhata hai.' },
      { question: 'Kya same-day tractor booking possible hai?', answer: 'Haan, jaisi availability ho waisi hi same-day booking bhi ki ja sakti hai.' },
    ],
    relatedBlogSlug: 'tractor-booking-online',
    image: '/gaonconnect1.webp',
  },
  {
    slug: 'jcb-rental',
    emoji: '🏗️',
    title: 'JCB Rental & JCB on Rent Service | GaonConnect',
    metaDescription: 'JCB rental service — apne gaon ke paas JCB near me book karein. Khudai, field leveling aur construction ke liye JCB on rent, transparent rate ke saath.',
    keywords: 'JCB rental, JCB on rent, JCB near me, JCB booking, JCB rent price, excavator rental',
    heroTitle: 'JCB Rental Service',
    heroSubtitle: 'Khudai, field leveling ya construction ke kaam ke liye JCB on rent — apne gaon ke paas se.',
    intro: [
      'GaonConnect par JCB rental service se aap talab khudai, khet leveling, naali banane ya construction se juda koi bhi kaam ke liye JCB book kar sakte hain.',
      'Booking karte waqt hi estimated rate dikh jaata hai, taaki kaam shuru hone se pehle budget clear rahe.',
    ],
    benefits: [
      { title: 'JCB Near Me', description: 'Apni location ke aas-paas available JCB owners turant dikh jaate hain.' },
      { title: 'Har Kaam Ke Liye', description: 'Khet leveling, talab khudai, naali banane — sabhi kaam ke liye JCB book karein.' },
      { title: 'Clear Pricing', description: 'Ghante ke hisaab se rate, booking se pehle hi dikh jaata hai.' },
      { title: 'Verified Operators', description: 'Sabhi JCB operators verified aur experienced hote hain.' },
    ],
    faqs: [
      { question: 'JCB rental price kis par depend karta hai?', answer: 'Rate kaam ki complexity, mitti ka type aur JCB ki site tak distance par depend karta hai — ghante ke hisaab se lagta hai.' },
      { question: 'Kya chhote kaam ke liye bhi JCB book ho sakti hai?', answer: 'Haan, chhoti khudai ya field leveling jaise chhote kaam ke liye bhi ghante ke hisaab se JCB book ki ja sakti hai.' },
    ],
    relatedBlogSlug: 'jcb-rental-price-guide',
    image: '/gaonconenct3.webp',
  },
  {
    slug: 'farm-equipment',
    emoji: '🌾',
    title: 'Farm Equipment Rental — Agriculture Machinery on Rent | GaonConnect',
    metaDescription: 'Farm equipment rental service — tractor, thresher, harvester jaisi agriculture machinery on rent, ek hi app mein. Agricultural equipment book karein GaonConnect se.',
    keywords: 'farm equipment rental, agriculture machinery, agricultural equipment, farm machinery on rent, kisan equipment rental',
    heroTitle: 'Farm Equipment Rental',
    heroSubtitle: 'Tractor, thresher, harvester — apni zaroorat ki agriculture machinery rent par lein, bina khareede.',
    intro: [
      'Har kisan ke liye tractor, thresher ya harvester khareedna possible nahi hota. GaonConnect ki farm equipment rental service se ye sabhi agricultural equipment sirf utne hi din ke liye book ki ja sakti hain, jitna kaam chale.',
      'Naye season mein naya equipment milta hai, maintenance ki tension bhi nahi rehti.',
    ],
    benefits: [
      { title: 'Ek Hi App', description: 'Tractor, thresher, harvester, JCB — sab agriculture machinery ek hi jagah book karein.' },
      { title: 'Kam Kharcha', description: 'Sirf kaam ke din ka hi payment — poora equipment khareedne ka bojh nahi.' },
      { title: 'Maintenance-Free', description: 'Machine ki maintenance ki chinta owner ki, aapki nahi.' },
      { title: 'Naya Equipment', description: 'Har season behtar, updated agricultural equipment use karein.' },
    ],
    faqs: [
      { question: 'Kaunsi agriculture machinery available hai?', answer: 'GaonConnect par tractor, JCB, thresher aur harvester — ye sabhi agricultural equipment rent par available hain.' },
      { question: 'Farm equipment rental lena kab faayde ka sauda hai?', answer: 'Agar zameen chhoti hai ya khaas kaam saal mein sirf kuch din hota hai, to rent par lena hamesha behtar hota hai.' },
    ],
    relatedBlogSlug: 'farm-equipment-rental-benefits',
    image: '/gaonconenct4.webp',
  },
  {
    slug: 'village-transport',
    emoji: '🚐',
    title: 'Village Transport & Rural Transport Service | GaonConnect',
    metaDescription: 'Village transport service jahan Ola-Uber nahi pahunchti. Auto, bike, car booking apne gaon ke paas — GaonConnect rural transport app se.',
    keywords: 'village transport, rural transport, village cab service, gaon transport app, dehat transport, rural ride booking',
    heroTitle: 'Village Transport Service',
    heroSubtitle: 'Jahan Ola-Uber nahi pahunchti, wahan GaonConnect pahunchta hai — apne gaon se auto, bike, car booking.',
    intro: [
      'GaonConnect ki village transport service khaas rural India ke liye banayi gayi hai — jahan sheher ki cab company nahi pahunchti, wahan bhi local driver partners ke through auto, bike aur car booking milti hai.',
      'Hospital jaana ho, train-bus pakadni ho, ya shaadi-function ke liye gaadi chahiye ho — sab ek hi app se.',
    ],
    benefits: [
      { title: 'Gaon Tak Pahunch', description: 'Jahan Ola-Uber nahi chalti, wahan bhi GaonConnect available hai.' },
      { title: 'Local Drivers', description: 'Aas-paas ke hi drivers, jo raaste aur area achhi tarah jaante hain.' },
      { title: 'Emergency Ke Liye Bhi', description: 'Hospital ya kisi bhi zaruri kaam ke liye turant booking.' },
      { title: 'Kai Vehicle Options', description: 'Auto, bike, car — zarurat ke hisaab se vehicle chunein.' },
    ],
    faqs: [
      { question: 'Kya GaonConnect sirf Madhya Pradesh mein available hai?', answer: 'Abhi GaonConnect Madhya Pradesh ke 20+ shahar aur gaon mein available hai, jahan bhi zarurat ho.' },
      { question: 'Emergency mein rural transport kitni jaldi milta hai?', answer: 'Aas-paas available drivers ki list turant dikhti hai, isliye booking chand minute mein ho jaati hai.' },
    ],
    relatedBlogSlug: 'village-transport-problems-solutions',
    image: '/gaonconnect5.webp',
  },
  {
    slug: 'agriculture-logistics',
    emoji: '🚚',
    title: 'Agriculture Logistics — Farm to Mandi Transport | GaonConnect',
    metaDescription: 'Agriculture logistics service — fasal katai ke baad mandi tak samaan pahunchane ke liye tempo booking, GaonConnect ke saath aasan aur samay par.',
    keywords: 'agriculture logistics, fasal transport, mandi tak samaan, tempo booking kisan, crop transport rural',
    heroTitle: 'Agriculture Logistics Service',
    heroSubtitle: 'Fasal katai ke baad mandi tak samaan pahunchana ab aasan — tempo booking ek hi app se.',
    intro: [
      'Fasal tayyar hone ke baad sabse bada sawaal hota hai — mandi tak samaan kaise pahunche. GaonConnect ki agriculture logistics service se tempo booking seedha khet ya ghar ke location se ki ja sakti hai.',
      'Samay par transport milne se fasal ki quality aur mandi ka rate dono behtar rehte hain.',
    ],
    benefits: [
      { title: 'Farm-to-Market', description: 'Khet se seedha mandi tak, ek hi booking mein.' },
      { title: 'Samay Par Delivery', description: 'Mandi ka time miss na ho, isliye booking turant confirm hoti hai.' },
      { title: 'Vehicle Size Ke Hisaab Se', description: 'Chhoti ya badi khep, dono ke liye sahi size ka tempo milta hai.' },
      { title: 'Clear Fare', description: 'Booking se pehle hi fare estimate pata chal jaata hai.' },
    ],
    faqs: [
      { question: 'Kya khet se seedha mandi tak booking ho sakti hai?', answer: 'Haan, tempo booking khet ya ghar ke location se seedha ki ja sakti hai aur samaan seedha mandi tak jaata hai.' },
      { question: 'Agriculture logistics ke liye kaunsa vehicle milta hai?', answer: 'Zarurat ke hisaab se alag-alag size ke tempo available hote hain.' },
    ],
    relatedBlogSlug: 'agriculture-logistics-mandi',
    image: '/gaonconnect6.webp',
  },
  {
    slug: 'auto-rickshaw-booking',
    emoji: '🛺',
    title: 'Auto Rickshaw Booking in Village & Rural Areas | GaonConnect',
    metaDescription: 'Auto rickshaw booking apne gaon ke aas-paas — GaonConnect se turant auto book karein, sasta aur bharosemand safar, jahan Ola-Uber nahi pahunchti.',
    keywords: 'auto rickshaw booking, auto booking village, rural auto service, gaon mein auto, auto near me rural',
    heroTitle: 'Auto Rickshaw Booking',
    heroSubtitle: 'Gaon se market, school ya station tak — auto rickshaw turant book karein.',
    intro: [
      'Gaon aur dehat ke ilaakon mein auto rickshaw roz ke safar ka sabse bharosemand zariya hai. GaonConnect par ye booking online, seedha aas-paas ke local auto drivers se ki ja sakti hai.',
      'Market jaana ho, school-college ya station tak pahunchna ho — sab ke liye auto booking ab ek app se ho jaati hai, bina roadside intezaar kiye.',
    ],
    benefits: [
      { title: 'Aas-Paas Ke Auto', description: 'Apni location ke najdeek available auto drivers turant dikh jaate hain.' },
      { title: 'Fair Rate', description: 'Distance ke hisaab se rate pehle hi pata chal jaata hai, koi bargaining nahi.' },
      { title: 'Family Ke Liye Safe', description: 'Trip sharing aur driver verification se safar surakshit rehta hai.' },
      { title: 'Roz Ke Safar Ke Liye', description: 'School, market, station — har roz ke chhote safar ke liye best option.' },
    ],
    faqs: [
      { question: 'Kya auto booking rural areas mein bhi available hai?', answer: 'Haan, GaonConnect khaas rural India ke liye banaya gaya hai, jahan auto booking gaon ke aas-paas bhi milti hai.' },
      { question: 'Auto ka rate kaise tay hota hai?', answer: 'Distance ke hisaab se rate app mein booking se pehle hi dikh jaata hai.' },
    ],
    relatedBlogSlug: 'auto-bike-car-village-booking',
    image: '/gaonconnect2.webp',
  },
  {
    slug: 'bike-taxi-booking',
    emoji: '🏍️',
    title: 'Bike Taxi Booking for Village & Rural Travel | GaonConnect',
    metaDescription: 'Bike taxi booking gaon aur dehat ke liye — sabse sasta aur tez safar ka tarika, GaonConnect app se turant book karein.',
    keywords: 'bike taxi rural, bike taxi booking, bike booking village, rural bike service, bike near me gaon',
    heroTitle: 'Bike Taxi Booking',
    heroSubtitle: 'Akele safar ke liye sabse tez aur sasta option — bike taxi turant book karein.',
    intro: [
      'Akele kahin jaana ho to bike taxi sabse tez aur sasta option hota hai. GaonConnect par bike taxi booking gaon aur dehat ke aas-paas ke ilaakon mein bhi milti hai.',
      'School, coaching ya nearby market — chhote safar ke liye bike taxi time aur paisa dono bachata hai.',
    ],
    benefits: [
      { title: 'Sabse Sasta Option', description: 'Chhote safar ke liye bike taxi sabse kam kiraya leti hai.' },
      { title: 'Traffic Se Bachav', description: 'Sankre raaston aur traffic mein bhi jaldi pahunch jaate hain.' },
      { title: 'Turant Availability', description: 'Aas-paas available bike drivers turant dikhte hain.' },
      { title: 'Verified Drivers', description: 'Sabhi bike drivers verified aur trusted hote hain.' },
    ],
    faqs: [
      { question: 'Bike taxi kis kaam ke liye sahi hai?', answer: 'Akele, chhoti distance ke liye bike taxi sabse tez aur sasta option hai — jaise school, coaching ya market jaana.' },
      { question: 'Kya bike taxi rural areas mein safe hai?', answer: 'Haan, sabhi drivers verified hote hain aur trip sharing feature se family bhi safar track kar sakti hai.' },
    ],
    relatedBlogSlug: 'auto-bike-car-village-booking',
    image: '/gaonconnect1.webp',
  },
  {
    slug: 'car-booking',
    emoji: '🚗',
    title: 'Car Booking for Rural India — Comfortable Village to City Travel | GaonConnect',
    metaDescription: 'Car booking rural India ke liye — gaon se sheher, comfort mein safar karein. GaonConnect se turant car book karein, fair rate ke saath.',
    keywords: 'car booking rural india, car booking village, gaon se sheher car, rural car service, car near me gaon',
    heroTitle: 'Car Booking Service',
    heroSubtitle: 'Gaon se sheher, aaram se aur comfort mein — car booking ek hi app se.',
    intro: [
      'Family ke saath ya lambi distance ka safar ho to car booking sabse comfortable option hota hai. GaonConnect par car booking gaon se sheher tak, seedha local drivers se milti hai.',
      'Hospital jaana ho, sheher mein kaam ho ya family trip — car booking se aaram se aur surakshit safar hota hai.',
    ],
    benefits: [
      { title: 'Comfort Aur Safety', description: 'Lambi distance ke liye car sabse aaramdayak aur safe option hai.' },
      { title: 'Family Ke Liye Best', description: 'Poore parivaar ke saath ek hi gaadi mein safar.' },
      { title: 'Gaon Se Sheher', description: 'Rural aur urban dono jagah car booking available.' },
      { title: 'Transparent Fare', description: 'Booking se pehle hi fare estimate dikh jaata hai.' },
    ],
    faqs: [
      { question: 'Kya car booking lambi distance ke liye bhi available hai?', answer: 'Haan, gaon se sheher ya doosre shehar tak bhi car booking ki ja sakti hai.' },
      { question: 'Car ka rate kaise pata chalta hai?', answer: 'Distance ke hisaab se estimated fare booking se pehle hi app mein dikh jaata hai.' },
    ],
    relatedBlogSlug: 'auto-bike-car-village-booking',
    image: '/gaonconnect5.webp',
  },
  {
    slug: 'wedding-car-booking',
    emoji: '🏛️',
    title: 'Wedding Car Booking — Shaadi Ki Gaadi Booking | GaonConnect',
    metaDescription: 'Wedding car booking aur shaadi ki gadi booking GaonConnect se karein — vivah, baraat aur function ke liye decorated gaadi turant book karein.',
    keywords: 'wedding car booking, shaadi ki gadi booking, vivah gaadi booking, baraat gaadi booking, function ke liye gaadi',
    heroTitle: 'Wedding Car Booking',
    heroSubtitle: 'Shaadi, baraat ya kisi bhi function ke liye gaadi — advance mein book karein, bina tension ke.',
    intro: [
      'Shaadi ke season mein gaadi milna sabse badi pareshani ban jaati hai. GaonConnect par wedding car booking advance mein ki ja sakti hai, taaki function ke din koi tension na ho.',
      'Baraat, mehmano ki aana-jaani ya saman le jaana — sabke liye alag-alag gaadi book kar sakte hain, ek hi app se.',
    ],
    benefits: [
      { title: 'Advance Booking', description: 'Function ki date tay hote hi booking kar sakte hain.' },
      { title: 'Kai Gaadi Options', description: 'Baraat aur mehmano ke liye alag-alag vehicle book karein.' },
      { title: 'Fixed Rate', description: 'Booking ke waqt hi rate confirm ho jaata hai, koi last-minute badhaava nahi.' },
      { title: 'Local Drivers', description: 'Aas-paas ke hi drivers jo raaste achhi tarah jaante hain.' },
    ],
    faqs: [
      { question: 'Shaadi ki gaadi kitne din pehle book karni chahiye?', answer: 'Jitni jaldi function ki date tay ho, utni jaldi booking karna behtar hota hai — season mein demand zyada rehti hai.' },
      { question: 'Kya baraat ke liye multiple gaadiyan book ho sakti hain?', answer: 'Haan, ek hi app se baraat, mehmano aur saman ke liye alag-alag gaadiyan book ki ja sakti hain.' },
    ],
    relatedBlogSlug: 'shaadi-ki-gadi-booking',
    image: '/gaonconenct3.webp',
  },
  {
    slug: 'goods-transport-booking',
    emoji: '🚚',
    title: 'Goods Transport & Tempo Booking for Village to Market | GaonConnect',
    metaDescription: 'Goods transport aur tempo booking GaonConnect se karein — saman, fasal ya samaan ek jagah se doosri jagah pahunchana ab aasan aur bharosemand.',
    keywords: 'tempo booking, goods transport booking, saman dhone ke liye tempo, rural goods transport, tempo near me',
    heroTitle: 'Goods Transport & Tempo Booking',
    heroSubtitle: 'Saman, fasal ya koi bhi khep — tempo booking ek hi app se, samay par delivery ke saath.',
    intro: [
      'Ghar shift karna ho, dukaan ka saman lana ho ya fasal mandi tak pahunchani ho — GaonConnect par tempo booking se ye sab kaam ek hi app se ho jaate hain.',
      'Vehicle ka size zarurat ke hisaab se choose kar sakte hain, aur booking se pehle hi fare estimate pata chal jaata hai.',
    ],
    benefits: [
      { title: 'Har Zarurat Ke Liye', description: 'Ghar shifting, dukaan ka saman ya fasal transport — sabke liye tempo booking.' },
      { title: 'Sahi Size Vehicle', description: 'Chhoti ya badi khep, dono ke liye sahi size ka tempo milta hai.' },
      { title: 'Samay Par Delivery', description: 'Booking confirm hote hi driver samay par pahunch jaata hai.' },
      { title: 'Clear Pricing', description: 'Distance aur load ke hisaab se fare pehle hi dikh jaata hai.' },
    ],
    faqs: [
      { question: 'Kya tempo booking khet se seedha mandi tak ho sakti hai?', answer: 'Haan, tempo booking khet ya ghar ke location se seedha ki ja sakti hai aur saman seedha mandi ya market tak jaata hai.' },
      { question: 'Goods transport ka rate kis par depend karta hai?', answer: 'Rate distance aur saman ke size/weight par depend karta hai — booking se pehle hi estimate mil jaata hai.' },
    ],
    relatedBlogSlug: 'agriculture-logistics-mandi',
    image: '/gaonconnect6.webp',
  },
];

export default servicePages;

export const getServicePageBySlug = (slug) => servicePages.find((page) => page.slug === slug);
